/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "language.switch": [],
    "jobs.public.index": [],
    "jobs.public.show": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "jobs.apply": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "my-applications.index": [],
    "jobs.index": [],
    "jobs.create": [],
    "jobs.show": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.applicants": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.store": [],
    "jobs.publish": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.destroy": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "applicants.show": [
        {
            "name": "application",
            "required": true,
            "binding": "id"
        }
    ],
    "applications.updateStatus": [
        {
            "name": "application",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register.job-seeker": [],
    "register.company": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
