name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '18'

jobs:
  # Backend Tests
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tutrabajojusto_test
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_pgsql, pgsql, redis, zip
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Copy .env
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          echo "Creating .env file from scratch"
          echo 'APP_NAME="TuTrabajoJusto"' > .env
          echo 'APP_ENV=testing' >> .env
          echo 'APP_KEY=' >> .env
          echo 'APP_DEBUG=true' >> .env
          echo 'APP_URL=http://localhost' >> .env
          echo '' >> .env
          echo 'LOG_CHANNEL=stack' >> .env
          echo 'LOG_DEPRECATIONS_CHANNEL=null' >> .env
          echo 'LOG_LEVEL=debug' >> .env
          echo '' >> .env
          echo 'DB_CONNECTION=pgsql' >> .env
          echo 'DB_HOST=localhost' >> .env
          echo 'DB_PORT=5432' >> .env
          echo 'DB_DATABASE=tutrabajojusto_test' >> .env
          echo 'DB_USERNAME=postgres' >> .env
          echo 'DB_PASSWORD=postgres' >> .env
          echo '' >> .env
          echo 'BROADCAST_DRIVER=log' >> .env
          echo 'CACHE_DRIVER=file' >> .env
          echo 'FILESYSTEM_DISK=local' >> .env
          echo 'QUEUE_CONNECTION=sync' >> .env
          echo 'SESSION_DRIVER=file' >> .env
          echo 'SESSION_LIFETIME=120' >> .env
          echo '' >> .env
          echo 'MEMCACHED_HOST=127.0.0.1' >> .env
          echo '' >> .env
          echo 'REDIS_HOST=127.0.0.1' >> .env
          echo 'REDIS_PASSWORD=null' >> .env
          echo 'REDIS_PORT=6379' >> .env
          echo '' >> .env
          echo 'MAIL_MAILER=smtp' >> .env
          echo 'MAIL_HOST=mailpit' >> .env
          echo 'MAIL_PORT=1025' >> .env
          echo 'MAIL_USERNAME=null' >> .env
          echo 'MAIL_PASSWORD=null' >> .env
          echo 'MAIL_ENCRYPTION=null' >> .env
          echo 'MAIL_FROM_ADDRESS="hello@example.com"' >> .env
          echo 'MAIL_FROM_NAME="${APP_NAME}"' >> .env
          echo '' >> .env
          echo 'AWS_ACCESS_KEY_ID=' >> .env
          echo 'AWS_SECRET_ACCESS_KEY=' >> .env
          echo 'AWS_DEFAULT_REGION=us-east-1' >> .env
          echo 'AWS_BUCKET=' >> .env
          echo 'AWS_USE_PATH_STYLE_ENDPOINT=false' >> .env
          echo '' >> .env
          echo 'PUSHER_APP_ID=' >> .env
          echo 'PUSHER_APP_KEY=' >> .env
          echo 'PUSHER_APP_SECRET=' >> .env
          echo 'PUSHER_HOST=' >> .env
          echo 'PUSHER_PORT=443' >> .env
          echo 'PUSHER_SCHEME=https' >> .env
          echo 'PUSHER_APP_CLUSTER=mt1' >> .env
          echo '' >> .env
          echo 'VITE_APP_NAME="${APP_NAME}"' >> .env
          echo 'VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"' >> .env
          echo 'VITE_PUSHER_HOST="${PUSHER_HOST}"' >> .env
          echo 'VITE_PUSHER_PORT="${PUSHER_PORT}"' >> .env
          echo 'VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"' >> .env
          echo 'VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"' >> .env
        fi

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install NPM dependencies
      run: npm ci

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for database to be ready
      run: sleep 10

    - name: Create database
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: tutrabajojusto_test
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
      run: |
        php artisan migrate --force
        php artisan db:seed --force

    - name: Execute tests (Unit and Feature)
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: tutrabajojusto_test
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
      run: php artisan test --coverage --min=80

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  # Frontend Tests
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_pgsql, pgsql, redis, zip

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Copy .env
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          echo "Creating .env file from scratch"
          echo 'APP_NAME="TuTrabajoJusto"' > .env
          echo 'APP_ENV=testing' >> .env
          echo 'APP_KEY=' >> .env
          echo 'APP_DEBUG=true' >> .env
          echo 'APP_URL=http://localhost' >> .env
          echo '' >> .env
          echo 'LOG_CHANNEL=stack' >> .env
          echo 'LOG_DEPRECATIONS_CHANNEL=null' >> .env
          echo 'LOG_LEVEL=debug' >> .env
          echo '' >> .env
          echo 'DB_CONNECTION=sqlite' >> .env
          echo 'DB_DATABASE=:memory:' >> .env
          echo '' >> .env
          echo 'BROADCAST_DRIVER=log' >> .env
          echo 'CACHE_DRIVER=file' >> .env
          echo 'FILESYSTEM_DISK=local' >> .env
          echo 'QUEUE_CONNECTION=sync' >> .env
          echo 'SESSION_DRIVER=file' >> .env
          echo 'SESSION_LIFETIME=120' >> .env
          echo '' >> .env
          echo 'MEMCACHED_HOST=127.0.0.1' >> .env
          echo '' >> .env
          echo 'REDIS_HOST=127.0.0.1' >> .env
          echo 'REDIS_PASSWORD=null' >> .env
          echo 'REDIS_PORT=6379' >> .env
          echo '' >> .env
          echo 'MAIL_MAILER=smtp' >> .env
          echo 'MAIL_HOST=mailpit' >> .env
          echo 'MAIL_PORT=1025' >> .env
          echo 'MAIL_USERNAME=null' >> .env
          echo 'MAIL_PASSWORD=null' >> .env
          echo 'MAIL_ENCRYPTION=null' >> .env
          echo 'MAIL_FROM_ADDRESS="hello@example.com"' >> .env
          echo 'MAIL_FROM_NAME="${APP_NAME}"' >> .env
          echo '' >> .env
          echo 'AWS_ACCESS_KEY_ID=' >> .env
          echo 'AWS_SECRET_ACCESS_KEY=' >> .env
          echo 'AWS_DEFAULT_REGION=us-east-1' >> .env
          echo 'AWS_BUCKET=' >> .env
          echo 'AWS_USE_PATH_STYLE_ENDPOINT=false' >> .env
          echo '' >> .env
          echo 'PUSHER_APP_ID=' >> .env
          echo 'PUSHER_APP_KEY=' >> .env
          echo 'PUSHER_APP_SECRET=' >> .env
          echo 'PUSHER_HOST=' >> .env
          echo 'PUSHER_PORT=443' >> .env
          echo 'PUSHER_SCHEME=https' >> .env
          echo 'PUSHER_APP_CLUSTER=mt1' >> .env
          echo '' >> .env
          echo 'VITE_APP_NAME="${APP_NAME}"' >> .env
          echo 'VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"' >> .env
          echo 'VITE_PUSHER_HOST="${PUSHER_HOST}"' >> .env
          echo 'VITE_PUSHER_PORT="${PUSHER_PORT}"' >> .env
          echo 'VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"' >> .env
          echo 'VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"' >> .env
        fi

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Run Playwright tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
        APP_ENV: testing
        APP_DEBUG: true
      run: npx playwright test --reporter=html

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  # Code Quality
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPStan
      run: composer analyse

    - name: Run Laravel Pint
      run: ./vendor/bin/pint --test

  # Security Scan
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Build and Deploy (only on main branch)
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, code-quality]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_pgsql, pgsql, redis, zip

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

    - name: Install NPM dependencies
      run: npm ci

    - name: Build frontend assets
      run: npm run build

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # Example: rsync, SSH, or cloud platform deployment

    - name: Notify deployment
      run: |
        echo "Deployment completed successfully!"
        # Add notification logic (Slack, Discord, etc.)
